2020-04-07 20:10:50,174 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-07 20:12:20,257 ERROR: Exception on /edit_profile [POST] [in /home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ansism/microblog/app/routes.py", line 85, in edit_profile
    db.session.commit()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', 'Esmu Flask iesācējs.', 2)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-04-07 20:49:25,255 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 09:14:52,243 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 09:28:19,222 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 09:28:32,239 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 10:43:46,788 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 10:51:09,634 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 10:54:25,365 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 10:59:56,838 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 11:03:11,019 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 11:05:22,321 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 11:08:38,130 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 11:52:57,036 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 13:18:03,281 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 13:18:31,546 ERROR: Exception on /explore [GET] [in /home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ansism/microblog/app/routes.py", line 27, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
NameError: name 'Post' is not defined
2020-04-08 13:19:46,004 ERROR: Exception on /index [GET] [in /home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ansism/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/ansism/microblog/app/routes.py", line 13, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-04-08 13:21:36,318 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 13:28:23,526 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 13:37:59,175 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 14:22:26,457 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 14:34:40,719 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 14:43:45,238 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:41]
2020-04-08 17:17:28,713 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:43]
2020-04-08 17:22:25,609 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:43]
2020-04-08 17:27:26,665 INFO: Microblog startup [in /home/ansism/microblog/app/__init__.py:43]
